# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')
env = env.Clone()

env.Append(CPPPATH=['#/src/'])
env.Append(LIBPATH=['#/lib/'])

obj = ['person.c']

env.aStaticLibrary("person_static", obj) 
env.aSharedLibrary("person_shared", obj) 

env.aSubs('unittest')
